export type CatalogTerms = {
  label: string
  value: string
  keywords: string[]
  requiredTerms: string[]
  blockedTerms: string[]
}

const sharedBlockedTerms = [
  'apple',
  'macbook',
  'ipad',
  'iphone',
  'imac',

  'battery',
  'adapter',
  'charger',
  'power supply',
  'ac adapter',
  'power adapter',
  'cable',
  'cord',

  'dock',
  'docking',
  'docking station',

  'sleeve',
  'case',
  'backpack',

  'lock',
  'keyed',
  'combination lock',
  'cable lock',
  'laptop lock',
  'notebook lock',
  'security lock',
  'security cable',
  'wedge-shaped',
  'wedge shaped',
  'n17',
  'kensington lock',

  'charging cart',
  'charging station',
  'storage station',
  'charge cart',

  'warranty',
  'service',
  'license',

  'privacy filter',
  'screen protector',
  'replacement',
  'spare',
]

const desktopAccessoryBlockedTerms = [
  'interface card',
  'interface cards',
  'flex io',
  'flex i/o',
  'i/o card',
  'io card',
  'usb port',
  'usb-c port',
  'type-c port',
  'hdmi port',
  'hdmi 2.1',

  'mounting kit',
  'mount kit',
  'mounting bracket',
  'bracket',
  'vesa mount',
  'wall mount',
  'under desk mount',
  'desktop mount',

  'riser',
  'riser card',
  'expansion card',
  'daughterboard',
  'daughter board',
  'module',
  'add-on card',
  'addon card',

  'faceplate',
  'bezel',
  'cover',
  'panel',
  'chassis kit',
  'internal cable',
  'internal connector',

  'keyboard',
  'mouse',
  'webcam',
  'speaker',
  'headset',
]

const monitorAccessoryBlockedTerms = [
  'mount',
  'mounting',
  'mounting kit',
  'mount kit',
  'mounting bracket',
  'bracket',
  'ceiling mount',
  'ceiling-mountable',
  'ceiling plate',
  'offset ceiling plate',
  'wall mount',
  'vesa mount',
  'display mount',
  'display stand',
  'monitor arm',
  'monitor stand',
  'monitor mount',
  'tv mount',
  'tilt mount',
  'fixed mount',
  'pole mount',
  'plate',

  'splitter',
  'hdmi splitter',
  'video splitter',
  'audio video splitter',
  'av splitter',
  'distribution amplifier',
  'switcher',
  'hdmi switch',
  'hdmi extender',
  'displayport adapter',
  'displayport cable',
  'hdmi cable',
  'video cable',
  'audio cable',
  'usb-c to hdmi',
  'usb to hdmi',
  'converter',

  'remote control',
  'remote',
  'tv remote',
  'press buttons',

  'wall plate',
  'faceplate',
  'backplate',
  'adapter plate',
  'mounting plate',
]

const workstationAccessoryBlockedTerms = [
  'optical drive',
  'dvd-rom',
  'dvd rom',
  'dvd drive',
  'blu-ray',
  'bluray',
  'cd-rom',
  'cd rom',

  'graphics card',
  'video card',
  'gpu',
  'nvidia quadro',
  'quadro sync',
  'sync ii',
  'sync card',
  'accelerator card',

  'controller card',
  'raid controller',
  'storage controller',
  'sas controller',
  'network adapter',
  'network card',
  'ethernet adapter',
  'fiber adapter',
  'fibre adapter',
  'hba',
  'host bus adapter',

  'workstation memory',
  'ecc memory',
  'server memory',
  'workstation ram',
  'memory kit',
  'drive bay',
  'drive cage',
  'drive tray',
  'hard drive tray',

  'power supply',
  'psu',
  'fan',
  'heatsink',
  'heat sink',
  'cooling module',
  'thermal module',

  'rail kit',
  'rack kit',
  'rack mount',
  'rackmount',
  'bezel',
  'front bezel',
  'side panel',
  'access panel',
  'replacement part',
  'spare part',
]

const computerPartBlockedTerms = [
  'memory module',
  'memory upgrade',
  'ram module',
  'ssd upgrade',
  'solid state drive',
  'hard drive',
  'm.2 drive',
  'nvme drive',
  'storage drive',
]

const printerSupplyBlockedTerms = [
  'toner',
  'ink',
  'ink cartridge',
  'cartridge',
  'drum',
  'maintenance',
  'maintenance box',
  'maintenance kit',
  'fuser',
  'printhead',
  'paper',
  'photo paper',
  'restickable photo paper',
  'sticker',
  'stickers',
  'label',
  'labels',
  'ribbon',
  'roll',
  'sheets',
  'pack',
  'pkg',
  'consumables',
]

const printerAccessoryBlockedTerms = [
  'tray',
  'paper tray',
  'extension tray',
  'tray cover',
  'cover',
  'stand',
  'cabinet',
  'caster',
  'feeder',
  'document feeder',
  'duplexer',
  'finisher',
  'stapler',
  'staple',
  'sorter',
  'output bin',
  'input tray',
  'media tray',

  'interface cable',
  'parallel cable',
  'rj-12',
  'rj12',
  'rj-45',
  'rj45',
  'usb cable',
  'powered usb',
  'y cable',
  'ethernet cable',
  'printer cable',

  'connectivity kit',
  'wireless connectivity kit',
  'network card',
  'print server',
  'jetdirect',
  'wifi adapter',
  'wi-fi adapter',
  'bluetooth adapter',

  'car adapter',
  'mobile car adapter',
  'power module',
  'power cord',
  'power cable',
  'power supply',
  'battery',
  'adapter',

  'cleaning kit',
  'cleaner',
  'replacement',
  'spare',
  'kit',
  'accessory',
  'accessories',
]

const printerProductTerms = [
  'printer',
  'laserjet',
  'officejet',
  'deskjet',
  'designjet',
  'pagewide',
  'multifunction printer',
  'all-in-one printer',
  'all in one printer',
  'wireless printer',
  'laser printer',
  'inkjet printer',
  'mfp',
  'scanner',
  'scan',
  'copy',
  'fax',
  'printing',
]

const nonPrinterBlockedTerms = [
  'laptop',
  'notebook',
  'elitebook',
  'probook',
  'thinkpad',
  'thinkbook',
  'latitude',
  'inspiron',
  'vostro',
  'chromebook',
  'vivobook',
  'travelmate',
  'desktop',
  'monitor',
  'display',
  'workstation',
  'server',
]

const publicCatalogBlockedTerms = [
  'engine',
  'pkg-desktop',
  'configuration',
  'configure to order',
  'cto',
]

export const catalogTerms: CatalogTerms[] = [
  {
    label: 'Laptops',
    value: 'laptops',
    keywords: [
      'ThinkBook laptop',
      'ThinkPad laptop',
      'EliteBook laptop',
      'ProBook laptop',
      'Latitude laptop',
      'Inspiron laptop',
      'Dell Vostro laptop',
      'Chromebook laptop',
      'Vivobook laptop',
      'TravelMate laptop',
      'business laptop',
      'notebook computer',

      'ZBook laptop',
      'ZBook mobile workstation',
      'ThinkPad mobile workstation',
      'ThinkPad P14s laptop',
      'ThinkPad P16s laptop',
      'ThinkPad P1 laptop',
      'mobile workstation laptop',
      'precision mobile workstation',
    ],
    requiredTerms: [
      'notebook',
      'laptop',
      'thinkbook',
      'thinkpad',
      'elitebook',
      'probook',
      'latitude',
      'inspiron',
      'vostro',
      'chromebook',
      'vivobook',
      'travelmate',
      'portable computer',

      'zbook',
      'mobile workstation',
      'thinkpad p14s',
      'thinkpad p16s',
      'thinkpad p1',
      'precision mobile',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...desktopAccessoryBlockedTerms,
      ...monitorAccessoryBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerAccessoryBlockedTerms,
      ...printerProductTerms,
      ...computerPartBlockedTerms,
      ...publicCatalogBlockedTerms,

      'monitor',
      'display',
      'stand',
      'laptop stand',
      'notebook stand',
      'cooling pad',
    ],
  },
  {
    label: 'Desktop PCs',
    value: 'desktops',
    keywords: [
      'OptiPlex desktop',
      'ThinkCentre desktop',
      'ProDesk desktop',
      'EliteDesk desktop',
      'Dell Vostro desktop',
      'Desktop PC',
      'Mini PC',
      'business desktop',
      'tower desktop',
    ],
    requiredTerms: [
      'desktop',
      'desktop pc',
      'mini pc',
      'optiplex',
      'thinkcentre',
      'prodesk',
      'elitedesk',
      'vostro desktop',
      'tower',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...desktopAccessoryBlockedTerms,
      ...monitorAccessoryBlockedTerms,
      ...workstationAccessoryBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerAccessoryBlockedTerms,
      ...printerProductTerms,
      ...computerPartBlockedTerms,
      ...publicCatalogBlockedTerms,

      'monitor',
      'display',
      'laptop',
      'notebook',
      'stand',
      'mount',
      'mounting',
      'adapter card',
      'port adapter',
      'option card',
      'replacement part',
      'spare part',
    ],
  },
  {
    label: 'Monitors',
    value: 'monitors',
    keywords: [
      'ThinkVision monitor',
      'UltraSharp monitor',
      'ProDisplay monitor',
      'Dell monitor',
      'HP monitor',
      'Lenovo monitor',
      'LED monitor',
      'LCD monitor',
      'business monitor',
      'computer monitor',
    ],
    requiredTerms: [
      'monitor',
      'computer monitor',
      'led monitor',
      'lcd monitor',
      'thinkvision',
      'ultrasharp',
      'prodisplay',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...desktopAccessoryBlockedTerms,
      ...monitorAccessoryBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerAccessoryBlockedTerms,
      ...printerProductTerms,
      ...publicCatalogBlockedTerms,

      'laptop',
      'notebook',
      'desktop',
      'arm',
      'privacy screen',
      'privacy filter',
    ],
  },
  {
    label: 'Printers',
    value: 'printers',
    keywords: [
      'LaserJet printer',
      'OfficeJet printer',
      'DeskJet printer',
      'Brother laser printer',
      'Canon laser printer',
      'Canon inkjet printer',
      'Epson printer',
      'multifunction printer',
      'wireless printer',
      'all-in-one printer',
      'business printer',
    ],
    requiredTerms: [
      'printer',
      'laserjet',
      'officejet',
      'deskjet',
      'designjet',
      'pagewide',
      'multifunction printer',
      'all-in-one printer',
      'all in one printer',
      'wireless printer',
      'laser printer',
      'inkjet printer',
      'mfp',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerAccessoryBlockedTerms,
      ...nonPrinterBlockedTerms,
      ...publicCatalogBlockedTerms,

      'warranty',
      'service',
      'license',
    ],
  },
  {
    label: 'All-in-One PCs',
    value: 'all-in-one',
    keywords: [
      'All-in-One PC',
      'All in One PC',
      'AIO Desktop',
      'ThinkCentre AIO',
      'HP All-in-One PC',
      'Dell All-in-One PC',
      'Lenovo All-in-One PC',
      'All-in-One Computer',
      'All in One Computer',
    ],
    requiredTerms: [
      'all-in-one pc',
      'all in one pc',
      'aio desktop',
      'thinkcentre aio',
      'all-in-one computer',
      'all in one computer',
      'desktop aio',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...desktopAccessoryBlockedTerms,
      ...monitorAccessoryBlockedTerms,
      ...workstationAccessoryBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerAccessoryBlockedTerms,
      ...printerProductTerms,
      ...computerPartBlockedTerms,
      ...publicCatalogBlockedTerms,

      'monitor only',
      'display only',
      'stand',
      'mount',
      'mounting',
    ],
  },
  {
    label: 'Business Workstations',
    value: 'workstations',
    keywords: [
      'Precision Workstation',
      'ThinkStation workstation',
      'Workstation desktop',
      'business workstation',
      'tower workstation',
      'desktop workstation',
      'Z workstation',
    ],
    requiredTerms: [
      'workstation',
      'precision workstation',
      'thinkstation',
      'workstation desktop',
      'desktop workstation',
      'tower workstation',
      'z workstation',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...desktopAccessoryBlockedTerms,
      ...monitorAccessoryBlockedTerms,
      ...workstationAccessoryBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerAccessoryBlockedTerms,
      ...printerProductTerms,
      ...computerPartBlockedTerms,
      ...publicCatalogBlockedTerms,

      'monitor',
      'display',
      'stand',
      'dock',
      'docking',

      'laptop',
      'notebook',
      'mobile workstation',
      'zbook',
      'thinkpad p14s',
      'thinkpad p16s',
      'thinkpad p1',
      'precision mobile',
    ],
  },
]

// Compatibility export.
// This lets ingramCatalogCache.ts import either catalogTerms or catalogCategories.
export const catalogCategories = catalogTerms
export type CatalogCategory = CatalogTerms