export type CatalogTerms = {
  label: string
  value: string
  keywords: string[]
  requiredTerms: string[]
  blockedTerms: string[]
}

const sharedBlockedTerms = [
  'apple',
  'macbook',
  'ipad',
  'iphone',
  'imac',

  'battery',
  'adapter',
  'charger',
  'power supply',
  'ac adapter',
  'power adapter',
  'cable',
  'cord',

  'dock',
  'docking',
  'docking station',

  'sleeve',
  'case',
  'backpack',

  'lock',
  'keyed',
  'combination lock',
  'cable lock',
  'laptop lock',
  'notebook lock',
  'security lock',
  'security cable',
  'wedge-shaped',
  'wedge shaped',
  'n17',
  'kensington lock',

  'charging cart',
  'charging station',
  'storage station',
  'charge cart',

  'warranty',
  'service',
  'license',

  'privacy filter',
  'screen protector',
  'replacement',
  'spare',
]

const desktopAccessoryBlockedTerms = [
  'interface card',
  'interface cards',
  'flex io',
  'flex i/o',
  'i/o card',
  'io card',
  'usb port',
  'usb-c port',
  'type-c port',
  'hdmi port',
  'hdmi 2.1',

  'mounting kit',
  'mount kit',
  'mounting bracket',
  'bracket',
  'vesa mount',
  'wall mount',
  'under desk mount',
  'desktop mount',

  'riser',
  'riser card',
  'expansion card',
  'daughterboard',
  'daughter board',
  'module',
  'add-on card',
  'addon card',

  'faceplate',
  'bezel',
  'cover',
  'panel',
  'chassis kit',
  'internal cable',
  'internal connector',

  'keyboard',
  'mouse',
  'webcam',
  'speaker',
  'headset',
]

const monitorAccessoryBlockedTerms = [
  'mount',
  'mounting',
  'mounting kit',
  'mount kit',
  'mounting bracket',
  'bracket',
  'ceiling mount',
  'ceiling-mountable',
  'ceiling plate',
  'offset ceiling plate',
  'wall mount',
  'vesa mount',
  'display mount',
  'display stand',
  'monitor arm',
  'monitor stand',
  'monitor mount',
  'tv mount',
  'tilt mount',
  'fixed mount',
  'pole mount',
  'plate',

  'splitter',
  'hdmi splitter',
  'video splitter',
  'audio video splitter',
  'av splitter',
  'distribution amplifier',
  'switcher',
  'hdmi switch',
  'hdmi extender',
  'displayport adapter',
  'displayport cable',
  'hdmi cable',
  'video cable',
  'audio cable',
  'usb-c to hdmi',
  'usb to hdmi',
  'converter',

  'remote control',
  'remote',
  'tv remote',
  'press buttons',

  'wall plate',
  'faceplate',
  'backplate',
  'adapter plate',
  'mounting plate',
]

const workstationAccessoryBlockedTerms = [
  'optical drive',
  'dvd-rom',
  'dvd rom',
  'dvd drive',
  'blu-ray',
  'bluray',
  'cd-rom',
  'cd rom',

  'graphics card',
  'video card',
  'gpu',
  'nvidia quadro',
  'quadro sync',
  'sync ii',
  'sync card',
  'accelerator card',

  'controller card',
  'raid controller',
  'storage controller',
  'sas controller',
  'network adapter',
  'network card',
  'ethernet adapter',
  'fiber adapter',
  'fibre adapter',
  'hba',
  'host bus adapter',

  'workstation memory',
  'ecc memory',
  'server memory',
  'workstation ram',
  'memory kit',
  'drive bay',
  'drive cage',
  'drive tray',
  'hard drive tray',

  'power supply',
  'psu',
  'fan',
  'heatsink',
  'heat sink',
  'cooling module',
  'thermal module',

  'rail kit',
  'rack kit',
  'rack mount',
  'rackmount',
  'bezel',
  'front bezel',
  'tower bezel',
  'side panel',
  'access panel',

  'dust filter',
  'air filter',
  'filter',
  'dust cover',

  'serial port',
  'serial port adapter',
  'serial adapter',
  '2nd flex io',
  'second flex io',
  'flex io',
  'flex i/o',
  'i/o module',
  'io module',
  'i/o adapter',
  'io adapter',
  'interface cards/adapter',
  'interface card',
  'interface cards',
  'adapter',
  'adapter card',
  'port adapter',
  'option card',

  'replacement part',
  'spare part',
]

const computerPartBlockedTerms = [
  'memory module',
  'memory upgrade',
  'ram module',
  'ssd upgrade',
  'solid state drive',
  'hard drive',
  'm.2 drive',
  'nvme drive',
  'storage drive',
]

const printerSupplyBlockedTerms = [
  'toner',
  'ink',
  'ink bottle',
  'ink tank',
  'ink cartridge',
  'cartridge',
  'drum',
  'imaging drum',
  'maintenance',
  'maintenance box',
  'maintenance kit',
  'fuser',
  'printhead',
  'print head',

  'paper',
  'photo paper',
  'matte paper',
  'glossy paper',
  'lustre',
  'luster',
  'restickable photo paper',
  'sticker',
  'stickers',
  'label',
  'labels',
  'ribbon',
  'roll',
  'sheets',
  'pack',
  'pkg',
  'consumables',

  'tape',
  'laminated tape',
  'label-making tape',
  'label making tape',
  'tz tape',
  'tze',
  'tze-',
  'tze-s',
]

const printerAccessoryBlockedTerms = [
  'tray',
  'paper tray',
  'extension tray',
  'tray cover',
  'cover',
  'stand',
  'cabinet',
  'caster',
  'feeder',
  'document feeder',
  'duplexer',
  'finisher',
  'stapler',
  'staple',
  'sorter',
  'output bin',
  'input tray',
  'media tray',

  'interface cable',
  'parallel cable',
  'rj-12',
  'rj12',
  'rj-45',
  'rj45',
  'usb cable',
  'powered usb',
  'y cable',
  'ethernet cable',
  'printer cable',

  'connectivity kit',
  'wireless connectivity kit',
  'network card',
  'print server',
  'jetdirect',
  'wifi adapter',
  'wi-fi adapter',
  'bluetooth adapter',

  'car adapter',
  'mobile car adapter',
  'power module',
  'power cord',
  'power cable',
  'power supply',
  'battery',
  'adapter',

  'cleaning kit',
  'cleaner',
  'replacement',
  'spare',
  'kit',
  'accessory',
  'accessories',

  'scanner',
  'flatbed scanner',
  'barcode scanner',
  'canoscan',
  'scanjet',

  'software license',
  'license',
  'upgrade',
]

const printerProductTerms = [
  'printer',
  'laserjet',
  'officejet',
  'deskjet',
  'designjet',
  'pagewide',
  'imageclass',
  'maxify',
  'pixma',
  'ecotank',
  'workforce',
  'multifunction printer',
  'all-in-one printer',
  'all in one printer',
  'wireless printer',
  'laser printer',
  'inkjet printer',
  'mfp',
]

const nonPrinterBlockedTerms = [
  'laptop',
  'notebook',
  'elitebook',
  'probook',
  'thinkpad',
  'thinkbook',
  'latitude',
  'inspiron',
  'vostro',
  'chromebook',
  'vivobook',
  'travelmate',
  'desktop',
  'monitor',
  'display',
  'workstation',
  'server',
]

const publicCatalogBlockedTerms = [
  'engine',
  'pkg-desktop',
  'configuration',
  'configure to order',
  'cto',
]

export const catalogTerms: CatalogTerms[] = [
  {
    label: 'Laptops',
    value: 'laptops',
    keywords: [
      'ProBook',
      'EliteBook',
      'ZBook',
      'OmniBook',
      'HP ProBook',
      'HP EliteBook',
      'HP ZBook',
      'HP OmniBook',
      'HP Notebook',
      'HP notebook PC',
      'HP business notebook',
      'HP business laptop',

      'ThinkPad',
      'ThinkBook',
      'Lenovo ThinkPad',
      'Lenovo ThinkBook',
      'ThinkPad T14',
      'ThinkPad T16',
      'ThinkPad E14',
      'ThinkPad E16',
      'ThinkPad P14s',
      'ThinkPad P16s',
      'ThinkPad P1',

      'Latitude',
      'Dell Latitude',
      'Dell Pro',
      'Dell Pro Laptop',
      'Dell Precision Mobile',
      'Precision Mobile',
      'Precision mobile workstation',
      'Dell Vostro laptop',
      'Inspiron laptop',

      'ExpertBook',
      'ASUS ExpertBook',
      'ASUS business laptop',
      'Vivobook laptop',

      'TravelMate',
      'Acer TravelMate',
      'Acer business laptop',

      'Galaxy Book',
      'Samsung Galaxy Book',

      'ThinkBook laptop',
      'ThinkPad laptop',
      'EliteBook laptop',
      'ProBook laptop',
      'Latitude laptop',
      'Chromebook laptop',
      'business laptop',
      'notebook computer',

      'ZBook laptop',
      'ZBook mobile workstation',
      'ThinkPad mobile workstation',
      'ThinkPad P14s laptop',
      'ThinkPad P16s laptop',
      'ThinkPad P1 laptop',
      'mobile workstation laptop',
      'precision mobile workstation',
    ],
    requiredTerms: [
      'notebook',
      'notebook pc',
      'laptop',
      'portable computer',

      'probook',
      'elitebook',
      'zbook',
      'omnibook',

      'thinkbook',
      'thinkpad',
      'thinkpad t14',
      'thinkpad t16',
      'thinkpad e14',
      'thinkpad e16',
      'thinkpad p14s',
      'thinkpad p16s',
      'thinkpad p1',

      'latitude',
      'inspiron',
      'vostro',
      'dell pro',
      'precision mobile',

      'chromebook',
      'vivobook',
      'expertbook',
      'travelmate',
      'galaxy book',

      'mobile workstation',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...desktopAccessoryBlockedTerms,
      ...monitorAccessoryBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerAccessoryBlockedTerms,
      ...printerProductTerms,
      ...computerPartBlockedTerms,
      ...publicCatalogBlockedTerms,

      'monitor',
      'display',
      'stand',
      'laptop stand',
      'notebook stand',
      'cooling pad',

      'thin client',
      'mobile thin client',
      'terminal',
      'windows iot',
      'enterprise thin client',
    ],
  },
  {
    label: 'Desktop PCs',
    value: 'desktops',
    keywords: [
      'OptiPlex',
      'ThinkCentre',
      'ProDesk',
      'EliteDesk',
      'Dell Vostro desktop',
      'Dell Pro Desktop',
      'HP Pro Mini',
      'HP Elite Mini',
      'HP ProDesk',
      'HP EliteDesk',
      'Lenovo ThinkCentre',
      'ASUS NUC',
      'Mini PC',
      'Desktop PC',
      'business desktop',
      'tower desktop',

      'OptiPlex desktop',
      'ThinkCentre desktop',
      'ProDesk desktop',
      'EliteDesk desktop',
    ],
    requiredTerms: [
      'desktop',
      'desktop pc',
      'mini pc',
      'optiplex',
      'thinkcentre',
      'prodesk',
      'elitedesk',
      'vostro desktop',
      'dell pro desktop',
      'pro mini',
      'elite mini',
      'nuc',
      'tower',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...desktopAccessoryBlockedTerms,
      ...monitorAccessoryBlockedTerms,
      ...workstationAccessoryBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerAccessoryBlockedTerms,
      ...printerProductTerms,
      ...computerPartBlockedTerms,
      ...publicCatalogBlockedTerms,

      'monitor',
      'display',
      'laptop',
      'notebook',
      'stand',
      'mount',
      'mounting',
      'adapter card',
      'port adapter',
      'option card',
      'replacement part',
      'spare part',

      'barebone',
      'barebones',
      'w/o ram',
      'without ram',
      'w/o storage',
      'without storage',
      'w/o os',
      'without os',
    ],
  },
  {
    label: 'Monitors',
    value: 'monitors',
    keywords: [
      'ThinkVision',
      'UltraSharp',
      'ProDisplay',
      'Dell monitor',
      'HP monitor',
      'Lenovo monitor',
      'Samsung monitor',
      'Philips monitor',
      'ViewSonic monitor',
      'ASUS monitor',
      'Acer monitor',
      'LED monitor',
      'LCD monitor',
      'business monitor',
      'computer monitor',

      'ThinkVision monitor',
      'UltraSharp monitor',
      'ProDisplay monitor',
    ],
    requiredTerms: [
      'monitor',
      'computer monitor',
      'led monitor',
      'lcd monitor',
      'thinkvision',
      'ultrasharp',
      'prodisplay',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...desktopAccessoryBlockedTerms,
      ...monitorAccessoryBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerAccessoryBlockedTerms,
      ...printerProductTerms,
      ...publicCatalogBlockedTerms,

      'laptop',
      'notebook',
      'desktop',
      'arm',
      'privacy screen',
      'privacy filter',
    ],
  },
  {
    label: 'Printers',
    value: 'printers',
    keywords: [
      'LaserJet printer',
      'OfficeJet printer',
      'DeskJet printer',
      'DesignJet printer',
      'PageWide printer',
      'imageCLASS printer',
      'MAXIFY printer',
      'PIXMA printer',
      'EcoTank printer',
      'WorkForce printer',
      'Brother printer',
      'Canon printer',
      'Epson printer',
      'HP printer',
      'Xerox printer',
      'multifunction printer',
      'wireless printer',
      'all-in-one printer',
      'business printer',
      'laser printer',
      'inkjet printer',
    ],
    requiredTerms: [
      'printer',
      'laserjet',
      'officejet',
      'deskjet',
      'designjet',
      'pagewide',
      'imageclass',
      'maxify',
      'pixma',
      'ecotank',
      'workforce',
      'multifunction printer',
      'all-in-one printer',
      'all in one printer',
      'wireless printer',
      'laser printer',
      'inkjet printer',
      'mfp',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerAccessoryBlockedTerms,
      ...nonPrinterBlockedTerms,
      ...publicCatalogBlockedTerms,

      'warranty',
      'service',
      'license',
      'software',
      'software license',
      'upgrade',
      'subscription',

      'scanner',
      'flatbed scanner',
      'barcode scanner',
      'canoscan',
      'scanjet',
      'document scanner',
      'image scanner',
    ],
  },
  {
    label: 'All-in-One PCs',
    value: 'all-in-one',
    keywords: [
      'All-in-One PC',
      'All in One PC',
      'AIO Desktop',
      'ThinkCentre AIO',
      'HP All-in-One PC',
      'Dell All-in-One PC',
      'Lenovo All-in-One PC',
      'All-in-One Computer',
      'All in One Computer',
      'desktop AIO',
    ],
    requiredTerms: [
      'all-in-one pc',
      'all in one pc',
      'aio desktop',
      'thinkcentre aio',
      'all-in-one computer',
      'all in one computer',
      'desktop aio',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...desktopAccessoryBlockedTerms,
      ...monitorAccessoryBlockedTerms,
      ...workstationAccessoryBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerAccessoryBlockedTerms,
      ...printerProductTerms,
      ...computerPartBlockedTerms,
      ...publicCatalogBlockedTerms,

      'monitor only',
      'display only',
      'stand',
      'mount',
      'mounting',
    ],
  },
  {
    label: 'Business Workstations',
    value: 'workstations',
    keywords: [
      'ThinkStation',
      'Precision Workstation',
      'Precision Tower',
      'HP Z Workstation',
      'HP Z2',
      'HP Z4',
      'HP Z6',
      'HP Z8',
      'Workstation desktop',
      'business workstation',
      'tower workstation',
      'desktop workstation',
      'Z workstation',

      'ThinkStation workstation',
    ],
    requiredTerms: [
      'workstation',
      'precision workstation',
      'precision tower',
      'thinkstation',
      'workstation desktop',
      'desktop workstation',
      'tower workstation',
      'z workstation',
      'hp z2',
      'hp z4',
      'hp z6',
      'hp z8',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...desktopAccessoryBlockedTerms,
      ...monitorAccessoryBlockedTerms,
      ...workstationAccessoryBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerAccessoryBlockedTerms,
      ...printerProductTerms,
      ...computerPartBlockedTerms,
      ...publicCatalogBlockedTerms,

      'monitor',
      'display',
      'stand',
      'dock',
      'docking',

      'laptop',
      'notebook',
      'mobile workstation',
      'zbook',
      'thinkpad p14s',
      'thinkpad p16s',
      'thinkpad p1',
      'precision mobile',
    ],
  },
]

// Compatibility export.
// This lets ingramCatalogCache.ts import either catalogTerms or catalogCategories.
export const catalogCategories = catalogTerms
export type CatalogCategory = CatalogTerms