export type CatalogTerms = {
  label: string
  value: string
  keywords: string[]
  requiredTerms: string[]
  blockedTerms: string[]
}

const sharedBlockedTerms = [
  'apple',
  'macbook',
  'ipad',
  'iphone',
  'imac',

  'battery',
  'adapter',
  'charger',
  'power supply',
  'ac adapter',
  'power adapter',
  'cable',
  'cord',

  'dock',
  'docking',
  'docking station',

  'sleeve',
  'case',
  'backpack',

  'warranty',
  'service',
  'license',

  'privacy filter',
  'screen protector',
  'replacement',
  'spare',
]

const computerPartBlockedTerms = [
  'memory module',
  'memory upgrade',
  'ram module',
  'ssd upgrade',
  'solid state drive',
  'hard drive',
  'm.2 drive',
  'nvme drive',
  'storage drive',
]

const printerSupplyBlockedTerms = [
  'toner',
  'ink',
  'ink cartridge',
  'cartridge',
  'drum',
  'maintenance',
  'maintenance box',
  'maintenance kit',
  'fuser',
  'printhead',
  'paper',
  'photo paper',
  'restickable photo paper',
  'sticker',
  'stickers',
  'label',
  'labels',
  'ribbon',
  'roll',
  'sheets',
  'pack',
  'pkg',
  'consumables',
]

const printerProductTerms = [
  'printer',
  'laserjet',
  'officejet',
  'deskjet',
  'designjet',
  'pagewide',
  'multifunction printer',
  'all-in-one printer',
  'all in one printer',
  'wireless printer',
  'laser printer',
  'inkjet printer',
  'mfp',
  'scanner',
  'scan',
  'copy',
  'fax',
  'printing',
]

const nonPrinterBlockedTerms = [
  'laptop',
  'notebook',
  'elitebook',
  'probook',
  'thinkpad',
  'thinkbook',
  'latitude',
  'inspiron',
  'vostro',
  'chromebook',
  'vivobook',
  'travelmate',
  'desktop',
  'monitor',
  'display',
  'workstation',
  'server',
]

const publicCatalogBlockedTerms = [
  'engine',
  'pkg-desktop',
  'configuration',
  'configure to order',
  'cto',
]

export const catalogTerms: CatalogTerms[] = [
  {
    label: 'Laptops',
    value: 'laptops',
    keywords: [
      'ThinkBook laptop',
      'ThinkPad laptop',
      'EliteBook laptop',
      'ProBook laptop',
      'Latitude laptop',
      'Inspiron laptop',
      'Dell Vostro laptop',
      'Chromebook laptop',
      'Vivobook laptop',
      'TravelMate laptop',
      'business laptop',
      'notebook computer',
    ],
    requiredTerms: [
      'notebook',
      'laptop',
      'thinkbook',
      'thinkpad',
      'elitebook',
      'probook',
      'latitude',
      'inspiron',
      'vostro',
      'chromebook',
      'vivobook',
      'travelmate',
      'portable computer',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerProductTerms,
      ...computerPartBlockedTerms,
      ...publicCatalogBlockedTerms,

      'monitor',
      'display',
      'stand',
      'laptop stand',
      'notebook stand',
      'cooling pad',
    ],
  },
  {
    label: 'Desktop PCs',
    value: 'desktops',
    keywords: [
      'OptiPlex desktop',
      'ThinkCentre desktop',
      'ProDesk desktop',
      'EliteDesk desktop',
      'Dell Vostro desktop',
      'Desktop PC',
      'Mini PC',
      'business desktop',
      'tower desktop',
    ],
    requiredTerms: [
      'desktop',
      'desktop pc',
      'mini pc',
      'optiplex',
      'thinkcentre',
      'prodesk',
      'elitedesk',
      'vostro desktop',
      'tower',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerProductTerms,
      ...computerPartBlockedTerms,
      ...publicCatalogBlockedTerms,

      'monitor',
      'display',
      'laptop',
      'notebook',
      'stand',
      'mount',
    ],
  },
  {
    label: 'Monitors',
    value: 'monitors',
    keywords: [
      'ThinkVision monitor',
      'UltraSharp monitor',
      'ProDisplay monitor',
      'Dell monitor',
      'HP monitor',
      'Lenovo monitor',
      'LED monitor',
      'LCD monitor',
      'business monitor',
      'computer monitor',
    ],
    requiredTerms: [
      'monitor',
      'computer monitor',
      'led monitor',
      'lcd monitor',
      'thinkvision',
      'ultrasharp',
      'prodisplay',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerProductTerms,
      ...publicCatalogBlockedTerms,

      'laptop',
      'notebook',
      'desktop',
      'mount',
      'stand',
      'arm',
      'monitor arm',
      'monitor stand',
      'privacy screen',
      'privacy filter',
    ],
  },
  {
    label: 'Printers',
    value: 'printers',
    keywords: [
      'LaserJet printer',
      'OfficeJet printer',
      'DeskJet printer',
      'Brother laser printer',
      'Canon laser printer',
      'Canon inkjet printer',
      'Epson printer',
      'multifunction printer',
      'wireless printer',
      'all-in-one printer',
      'business printer',
    ],
    requiredTerms: [
      'printer',
      'laserjet',
      'officejet',
      'deskjet',
      'designjet',
      'multifunction printer',
      'all-in-one printer',
      'all in one printer',
      'wireless printer',
      'laser printer',
      'inkjet printer',
      'mfp',
    ],
    blockedTerms: [
      ...printerSupplyBlockedTerms,
      ...nonPrinterBlockedTerms,
      ...publicCatalogBlockedTerms,

      'warranty',
      'service',
      'license',
      'paper tray',
    ],
  },
  {
    label: 'All-in-One PCs',
    value: 'all-in-one',
    keywords: [
      'All-in-One PC',
      'All in One PC',
      'AIO Desktop',
      'ThinkCentre AIO',
      'HP All-in-One PC',
      'Dell All-in-One PC',
      'Lenovo All-in-One PC',
      'All-in-One Computer',
      'All in One Computer',
    ],
    requiredTerms: [
      'all-in-one pc',
      'all in one pc',
      'aio desktop',
      'thinkcentre aio',
      'all-in-one computer',
      'all in one computer',
      'desktop aio',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerProductTerms,
      ...computerPartBlockedTerms,
      ...publicCatalogBlockedTerms,

      'monitor only',
      'display only',
      'stand',
      'mount',
    ],
  },
  {
    label: 'Business Workstations',
    value: 'workstations',
    keywords: [
      'Precision Workstation',
      'ZBook workstation',
      'ThinkStation workstation',
      'Workstation desktop',
      'Mobile Workstation',
      'business workstation',
    ],
    requiredTerms: [
      'workstation',
      'precision workstation',
      'mobile workstation',
      'zbook',
      'thinkstation',
    ],
    blockedTerms: [
      ...sharedBlockedTerms,
      ...printerSupplyBlockedTerms,
      ...printerProductTerms,
      ...computerPartBlockedTerms,
      ...publicCatalogBlockedTerms,

      'monitor',
      'display',
      'stand',
      'dock',
      'docking',
    ],
  },
]

// Compatibility export.
// This lets ingramCatalogCache.ts import either catalogTerms or catalogCategories.
export const catalogCategories = catalogTerms
export type CatalogCategory = CatalogTerms